[desktop]
depends = ["shell", "kitty", "neovim", "fonts"]

[shell.files]
"zsh/plugins" = "~/.oh-my-zsh/custom/plugins"
"zsh/zshrc" = "~/.zshrc"

[kitty.files]
kitty = "~/.config/kitty"

[neovim.files]
nvim = "~/.config/nvim"

[fonts.files]
fonts = "~/.local/share/fonts"
