[desktop]
depends = ["shell", "kitty", "neovim", "lazyvim", "thefuck"]

[shell.files]
zshrc = "~/.zshrc"

[kitty.files]
kitty = "~/.config/kitty"

[neovim.files]
nvim = "~/.config/nvim"

[lazyvim.files]
lazy = "~/.local/share/nvim/lazy"

[thefuck.files]
thefuck = "~/.config/thefuck"
