[desktop]
depends = ["shell", "kitty", "neovim"]

[shell.files]
"zsh/plugins" = "~/.oh-my-zsh/custom/plugins"
"zsh/zshrc" = "~/.zshrc"

[kitty.files]
kitty = "~/.config/kitty"

[neovim.files]
nvim = "~/.config/nvim"
