[desktop]
depends = ["shell", "ghostty", "neovim", "fonts", "hammerspoon"]

[shell.files]
"zsh/plugins" = "~/.oh-my-zsh/custom/plugins"
"zsh/zshrc" = "~/.zshrc"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[neovim.files]
nvim = "~/.config/nvim"

[fonts.files]
fonts = "~/.local/share/fonts"

[hammerspoon.files]
"hammerspoon/init.lua" = "~/.hammerspoon/init.lua"
