export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"

# path
path+=/usr/bin
path+=$HOME/.local/share/bob/nvim-bin
path+=/opt/cuda/bin
export PATH

plugins=(
    git
    zsh-autosuggestions
    zsh-completions
    fzf
)

fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh
. "$HOME/.cargo/env"

# Node18
PATH="/opt/homebrew/opt/node@18/bin:$PATH"

# fzf
export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Alias LazyGit
alias lg="lazygit"
alias ld="lazydocker"

# Alias Nvim
alias vim="nvim"
